### PR TITLE
oop-cop

### LINKED ISSUE #91: Fix `pom.xml` to publish `oopcop` artifact

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #91

---

## PR-Codex overview
This PR updates the project configuration and code to rename the artifact from "sa-tan" to "oop-cop".

### Detailed summary
- Renamed artifactId from "sa-tan" to "oop-cop" in pom.xml files.
- Updated SCM URLs in pom.xml files to point to the new repository "oop-cop".
- Removed a log statement in ValidateMojo.java.
- Updated the name and URL in pom.xml to reflect the new artifact name "oop-cop".
- Updated the URL in ciManagement section of pom.xml to point to the new repository "oop-cop".

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-01T17:01:11.210490``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
