### PR TITLE
real examples in README, more accurate suppression description

### PR DESCRIPTION
**Pull request by h1alexbel**
@l3r8yJ take a look, please

---

## PR-Codex overview
This PR focuses on two code checks: MutableStateCheck and ErSuffixCheck. The notable changes are:

- Renamed the section "Mutable Objects" to "MutableStateCheck"
- Renamed the class "MyValidClass" to "Pet" and updated its constructor
- Renamed the class "MyInvalidClass" to "Pet" and updated its constructor
- Added a code example for suppressing the MutableStateCheck using `@SuppressWarnings`
- Renamed the section "Parsers, Validators, Controllers" to "ErSuffixCheck"
- Updated the class "FileParser" to comply with the ErSuffixCheck
- Added a code example for suppressing the ErSuffixCheck using `@SuppressWarnings`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-08T07:40:06.885461``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by l3r8yJ — APPROVED** [review]

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
