### PR TITLE
to oop cop

### LINKED ISSUE #103: self dependency

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #103 

---

### Focus of this PR:
This PR focuses on refactoring class and method names in the codebase to improve clarity and consistency.

### Detailed summary:
- Renamed `WrongMethodSignatureComplaint` to `WrongMethodSignature`
- Renamed `CompositeLongClassName` to `CompositeClassName`
- Renamed `WrongClassNamingComplaint` to `WrongClassNaming`
- Renamed `CompositeErNamedClass` to `CompositeErNamed`
- Renamed `CompositeMethodsContainsAssigment` to `AssigmentCheck`
- Updated Maven plugin configuration to use `oop-cop` version 0.1.6
- Updated dependencies and plugin versions in `pom.xml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-02T01:19:59.235423``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
