### PR TITLE
no sa-tan

### PR DESCRIPTION
**Pull request by l3r8yJ**
## PR-Codex overview
This PR focuses on renaming the annotations package from "Sa-tan" to "Oop-cop". It also updates the relevant links and badges accordingly.

### Detailed summary
- Renamed the annotations package from "Sa-tan" to "Oop-cop"
- Updated the README.md file to reflect the changes in package name
- Updated the links and badges in the README.md file to point to the new package name

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-02T00:39:59.956534``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
