### PR TITLE
feat(#106): Use Concrete Version in README

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. Add concrete version of the plugin to README (`0.1.6`)
2. Add the script that will automatically update the version in README.

Closes: #106

---

### Detailed summary

- Added version `0.1.6` to `README.md` file.
- Added a new GitHub Actions workflow file `up.yaml`.
- The workflow triggers on `push` to `master` branch or any tag.
- The workflow runs on `ubuntu-22.04` environment.
- The workflow fetches tags and updates the version in `README.md`.
- The workflow creates a pull request to update the plugin version in the README file.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@volodya-lombrozo thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Could you take a look, please?

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-02T14:20:03.633595``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by l3r8yJ — APPROVED** [review]
looks good to me!

**Comment by l3r8yJ** [comment]
@volodya-lombrozo thank you for contribution! @rultor merge

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
