### PR TITLE
Suppressions for checks, more unit tests

### LINKED ISSUE #85: Supression for LongClassNameCheck
Let's add a suppression mechanism for LongClassNameCheck:
```java
@SupressWarnings("OCOP.LongClassNameCheck")
class ThisIsTooLongName {}
```

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #85

---

### Detailed summary
- Added a new class `VeryLongClassName` in two different locations with different annotations.
- Added a new configuration in `pom.xml`.
- Renamed the method `parsesClassNamesInRightFormat` to `parsesInvalidClassNamesInRightFormat` in `ClassNamesTest`.
- Modified the imports in `IsSuppressedTest`.
- Added two new test methods in `LongClassNameCheckTest` and `MethodChangesStateTest`.
- Added a new interface `CodeClass` and implemented it in `CodeClass.java`.
- Added a new interface `Code` and implemented it in `Code.java`.
- Added a new class `Declaration` and implemented `CodeClass` in `Declaration.java`.
- Added a new class `Default` and implemented `Code` in `Default.java`.
- Added a new interface `Code` and implemented it in `Code.java`.
- Added a new class `Default` and implemented `Code` in `Default.java`.

> The following files were skipped due to too many changes: `src/main/java/ru/l3r8y/parser/Default.java`, `src/main/java/ru/l3r8y/parser/ClassNames.java`, `src/main/java/ru/l3r8y/parser/IgnoresSuppressed.java`, `src/test/java/ru/l3r8y/extensions/SuppressedLongClassName.java`, `src/test/java/ru/l3r8y/parser/DeclarationTest.java`, `src/test/java/ru/l3r8y/extensions/ParserDeclaration.java`, `src/test/java/ru/l3r8y/extensions/ManySuppressionsDeclaration.java`, `src/test/java/ru/l3r8y/parser/DefaultTest.java`, `src/test/java/ru/l3r8y/parser/SuppressedChecksTest.java`, `src/test/java/ru/l3r8y/parser/IgnoresSuppressedTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2024-01-08T12:10:03.968245``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@l3r8yJ take a look, please

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel looks cool

**Comment by l3r8yJ** [comment]
@rultor merge

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
